### ISSUE TITLE
Duplicate 3DSX and SMDH files in /<zip root>/ and /vmac/

### ISSUE THREAD

**Issue by PolarisBeaver** [TaraHoleInIt/mini-vmac-3ds-plus4M#1]
Additionally, the filesizes betwen the duplicate minivmac-3ds-plus4M.3dsx files differ, can you release with 1 single (updated) copy of the 3dsx and smdh files instead?

**Comment by TaraHoleInIt** [comment]
Updated zip file, the correct binaries are in the correct place which is in the vmac folder.
